spring.application.name=book-storage-service
server.port=${STORAGE_PORT}
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:${STORAGE_DB_PORT}/${STORAGE_DB_NAME}
spring.datasource.username=${STORAGE_DB_USER}
spring.datasource.password=${STORAGE_DB_PASS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.kafka.bootstrap-servers=kafka:${KAFKA_PORT}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855