#!/bin/bash

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF

CREATE DATABASE IF NOT EXISTS \`${TRACKER_DB_NAME}\`;
CREATE DATABASE IF NOT EXISTS \`${STORAGE_DB_NAME}\`;
CREATE DATABASE IF NOT EXISTS \`${AUTH_DB_NAME}\`;

CREATE USER IF NOT EXISTS '${TRACKER_DB_USER}'@'%' IDENTIFIED BY '${TRACKER_DB_PASS}';
CREATE USER IF NOT EXISTS '${STORAGE_DB_USER}'@'%' IDENTIFIED BY '${STORAGE_DB_PASS}';
CREATE USER IF NOT EXISTS '${AUTH_DB_USER}'@'%' IDENTIFIED BY '${AUTH_DB_PASS}';

GRANT ALL PRIVILEGES ON \`${TRACKER_DB_NAME}\`.* TO '${TRACKER_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${STORAGE_DB_NAME}\`.* TO '${STORAGE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${AUTH_DB_NAME}\`.* TO '${AUTH_DB_USER}'@'%';

FLUSH PRIVILEGES;

EOF